// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAAp7A-PCMVsjSGSOI45cipi-rNw7EsBc',
    appId: '1:365688545018:web:8f341c482943f93ace7343',
    messagingSenderId: '365688545018',
    projectId: 'meditriage-c0915',
    authDomain: 'meditriage-c0915.firebaseapp.com',
    storageBucket: 'meditriage-c0915.firebasestorage.app',
    measurementId: 'G-0F97QBD0JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR3wxRK-LzOefZtrNhQi5Id2J8YDQG92A',
    appId: '1:365688545018:android:2bff4c5073b834a9ce7343',
    messagingSenderId: '365688545018',
    projectId: 'meditriage-c0915',
    storageBucket: 'meditriage-c0915.firebasestorage.app',
  );

}